### ISSUE TITLE
Работает ли на +380 спаммер? 

### ISSUE THREAD

**Issue by mrazazazaza** [ebankoff/Beast_Bomber#28]
Бомблю свой же телефон на +380 ничего не доходит, никаких ошибок, ничего. В чём может быть проблема? 
![image](https://user-images.githubusercontent.com/102682319/160956820-a303ca1a-60df-4e27-aed5-086c42d57bce.png)

**Comment by ebankoff** [comment]
Проблема может быть в том, что в данный момент мало сервисов для спама поддерживают Украинские номера. Вскоре планирую добавить больше!
