### ISSUE TITLE
Discord spam not working

### ISSUE THREAD

**Issue by TesterLester55555** [ebankoff/Beast_Bomber#34]
It seems like this issue was  already submitted a while ago but i cant seem to get it working. All python modules were installed today and the chrome driver was also installed now, correct discord token and the user is in my server but it still gets an error. Any ideas on how to fix it?
![image](https://user-images.githubusercontent.com/105131860/167273302-e0dde87f-02da-4aee-b0aa-1f719035d50a.png)

**Comment by ebankoff** [comment]
Try using a proxy, sometimes it helps. It may also be due to the fact that Discord has changed something and messages are sent somehow differently, I will try to figure it out.
