### ISSUE TITLE
Telegram spammer doesn't working

### ISSUE THREAD

**Issue by mrksbgg** [ebankoff/Beast_Bomber#36]
EN:
I'm using script on Windows 10

RU:
Я использую этот скрипт на Windows 10

┏━━━━┓ ┏┓
┃┏┓┏┓┃ ┃┃
┗┛┃┃┣┻━┫┃┏━━┳━━┳━┳━━┳┓┏┓
  ┃┃┃ ━┫┃┃ ━┫┏┓┃┏┫┏┓┃┗┛┃
  ┃┃┃ ━┫┗┫ ━┫┗┛┃┃┃┏┓┃┃┃┃
  ┗┛┗━━┻━┻━━┻━┓┣┛┗┛┗┻┻┻┛
            ┏━┛┃
            ┗━━┛

Proxy? yes/no: no
Victim name: SomeUser
Number of messages: 150
Message: test

Press Enter to start

DevTools listening on ws://127.0.0.1:53753/devtools/browser/why?

━━━━━━━━━━━Error━━━━━━━━━━━

Exit? yes/no:

**Comment by ebankoff** [comment]
This error usually occurs because google chrome and chromedriver are incompatible. Try to update google chrome and install the latest version of [chromedriver ](https://chromedriver.chromium.org)(unzip it and put it in the "core" folder of the bomber).
