### ISSUE TITLE
Gmail problem

### ISSUE THREAD

**Issue by eccentricPACHARA** [ebankoff/Beast_Bomber#39]
Gmail spam problem
I think we cant longer use normal gmail like @gmail domain cuz I think we cant enable "less secure apps" anymore
and if u dont enable "less secure app" there will be some traceback which mean it fail

so I try to use Yandex then it say Attacking Process success but when I check target email there is no mail coming in so idk if the mail spam api is still working or not maybe it is outdated and you need to update.

**Comment by ebankoff** [comment]
I'll see what I can do.

**Comment by eccentricPACHARA** [comment]
alright bro
