### ISSUE TITLE
Country number is not supported

### ISSUE THREAD

**Issue by aakash-priyadarshi** [ebankoff/Beast_Bomber#48]
Hi, I was trying to use the SMS spammer on my own number. But it seems my Indian number is not supported. Can you help me with adding my country code to the script? What changes I must do and where.

**Comment by aakash-priyadarshi** [comment]
Can you help me with adding my country code to the script? What changes I must do and where.

**Comment by ebankoff** [comment]
Hello, it is unlikely that I will be able to add support for Indian phone numbers🤷
