### ISSUE TITLE
Discord 

### ISSUE THREAD

**Issue by erikpepsila** [ebankoff/Beast_Bomber#49]
![discrod](https://user-images.githubusercontent.com/113862323/190929622-9d7d6023-ec67-41a2-a68d-923b75593884.png)
Такая проблема, Прокси включен, ID верные ( пробовал с 4 разными, одно и тоже) Токен как по инструкции.

**Comment by ebankoff** [comment]
У discord изменилась логика отправки сообщений, скрипт я еще не обновлял.
