### ISSUE TITLE
Telegram

### ISSUE THREAD

**Issue by erikpepsila** [ebankoff/Beast_Bomber#50]
![telegram](https://user-images.githubusercontent.com/113862323/190929667-451a00d3-e1c5-4c0e-b990-ffb180d16f8b.png)
Не впервые ошибка, пробовал на нескольких никах, везде тоже самое, прокси есть, браузер версия последняя, драйвер тот - аналогично, на фоне он кста запушен.  И еще, если выбрать Proxy - yes ,то будет в любом случае ошибка ( в телеграм и Дискорд бомбере, особено в дискорд версии бомбера, там если выбрать no, то хотябы будут попытки, а если yes, то будет ошибка ( прокси включен))

**Comment by ebankoff** [comment]
Попробуйте поставить другую версию [chromedriver](https://chromedriver.chromium.org): скачайте с официального сайта подходящую версию, распакуйте ее и поместите в папку core бомбера. Если не помогло, переустановите Python вместе со всеми библиотеками. Что касается discord, у них  изменилась логика отправки сообщений, а скрипт я еще не обновлял.
