### ISSUE TITLE
Не работает СМС-спам для +7

### ISSUE THREAD

**Issue by lasn77** [ebankoff/Beast_Bomber#52]
Привет. Запускаю спамер, выбираю СМС, прокси нет, антикапча нет, код страны +7, ввожу номер, время атаки 10, количество потоков 2. Пишет "Атака", но СМС не приходят. В чём может быть дело? Проверил на двух номерах. Windows 10. Версия python 3.10.1

**Comment by ebankoff** [comment]
Вероятно из-за того, что я давно не обновлял сервисы для спама, бомбер плохо работает. Если нужен норм спам, лучше пользоваться Telegram ботом: https://t.me/beast_bomberr_bot
