### ISSUE TITLE
I have a problem with installing requirements

### ISSUE THREAD

**Issue by jrALPO** [ebankoff/Beast_Bomber#56]
I have a problem with installing requirements
![Ekran görüntüsü 2022-11-21 010254](https://user-images.githubusercontent.com/68761740/202931375-c3bcc913-413c-4443-81d2-a1e35a545b20.png)

**Comment by ebankoff** [comment]
This seems to be a problem with Python, try installing an earlier version (I recommend [3.10.8](https://www.python.org/downloads/release/python-3108/)) and uninstalling the current one. Then reinstall all the libraries. No other ideas
