### ISSUE TITLE
Aborted ( core dumped )

### ISSUE THREAD

**Issue by jakubgaba** [ebankoff/Beast_Bomber#57]
![Screenshot from 2022-11-26 18-35-12](https://user-images.githubusercontent.com/86305055/204101672-e5969302-30d5-41a4-8cd2-dd9d2cecdbeb.png)

What that means ?

**Comment by ebankoff** [comment]
It seems to be related to your PC, try reinstalling python and google this error.

**Comment by jakubgaba** [comment]
Not working :( .... i treid to track it with gdb but also nothing and other python programs works...
